# Generated by Django 3.0.6 on 2020-07-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=200)),
                ('email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('detail', models.TextField(max_length=1000)),
                ('email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200)),
                ('passed', models.DateField()),
                ('score', models.CharField(max_length=100)),
                ('email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Contact')),
            ],
        ),
    ]
